{"name": "test_cppk", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_cppk\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_cppk', 'cppk')", "trace": "self = <Test_MT.TestOther object at 0x000001D180592BA8>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_cppk\")\n    def test_cppk (self):\n>       assert AutoTest(number, mac, name, '_P_cppk', 'cppk') == True, \"Ошибка в ходе выполнения теста _P_cppk\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_cppk\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_cppk', 'cppk')\n\nTest_MT.py:106: AssertionError"}, "attachments": [{"name": "log", "source": "e506c4de-6ef7-4c10-ad3b-53d7ebf282d4-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b6f4e957-c654-46b3-975d-563f924e91dc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9cdbf53f-464a-43c8-99cd-6e7e2b39b07f-attachment.txt", "type": "text/plain"}], "start": 1652251393112, "stop": 1652251586477, "uuid": "e6f83bf8-e994-41e4-acd5-c60af658d2ea", "historyId": "e453b87c8e20737f2e5240696f4d8277", "testCaseId": "e3d132f9150e145b9291a771e93e05c0", "fullName": "Test_MT.TestOther#test_cppk", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_cppk"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "3836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}