{"name": "test_bus207", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus207\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')", "trace": "self = <Test_MT.TestOther object at 0x000001DBCEFAA8D0>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_TTM_v5\")\n    def test_bus207(self):\n>       assert AutoTest(number, mac, name, '_P_TTM_v5', 'bus207') == True, \"Ошибка в ходе выполнения теста bus207\"\nE       AssertionError: Ошибка в ходе выполнения теста bus207\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')\n\nTest_MT.py:134: AssertionError"}, "attachments": [{"name": "log", "source": "a71ba78e-7f0c-4a0a-8668-ab4333c12c4d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "0e232c13-b0cc-4d02-9baf-3b1b38c4fe0f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a2f5c45c-7f6f-46f9-9390-4fd6929a97df-attachment.txt", "type": "text/plain"}], "start": 1652111980665, "stop": 1652112174896, "uuid": "5ee257b1-53e3-480f-aa07-5811bec2ad1b", "historyId": "3369cd05539770f0c09511c571a4094b", "testCaseId": "bc0a014b62f50edbcb39f57be6bfbe2a", "fullName": "Test_MT.TestOther#test_bus207", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_TTM_v5"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "8068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}