{"name": "test_eos_beeline", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')", "trace": "self = <Test_MT.TestEOS object at 0x0000019C94878358>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_beeline\")\n    def test_eos_beeline (self):\n>       assert AutoTest(number, mac, name, '_P_dit_beeline', 'beeline') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_beeline\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')\n\nTest_MT.py:86: AssertionError"}, "attachments": [{"name": "log", "source": "11932eaf-3433-48f0-9f55-f3b4bdbfd1a5-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "a9ff112c-51b2-4ce8-9dac-88d6efd8e347-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "514f29dc-b448-413d-94d5-545ff1945f0b-attachment.txt", "type": "text/plain"}], "start": 1651965233622, "stop": 1651965357218, "uuid": "8e928a05-cd47-4a3d-82a9-cc7e5de5b676", "historyId": "e22ae9fe984354816df9ee71a888005b", "testCaseId": "6681ab98911e15b281dbcc8f74f0892b", "fullName": "Test_MT.TestEOS#test_eos_beeline", "labels": [{"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_dit_beeline"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "4240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}