{"name": "test_eos_guest", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_guest_wifi\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_guest_wifi', 'guest')", "trace": "self = <Test_MT.TestEOS object at 0x000001A8E73F07F0>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_guest_wifi\")\n    def test_eos_guest (self):\n>       assert AutoTest(number, mac, name, '_P_dit_guest_wifi', 'guest') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                  \" теста _P_dit_guest_wifi\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_guest_wifi\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_guest_wifi', 'guest')\n\nTest_MT.py:67: AssertionError"}, "attachments": [{"name": "log", "source": "c70f64a5-fc1a-4cf1-bbdf-a3ccb28128c7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9cf977b2-1f08-4451-a7b0-0a8388e9308d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "aeae8917-0afc-4ee6-bd71-9fe1c3565fa2-attachment.txt", "type": "text/plain"}], "start": 1651662268796, "stop": 1651662518233, "uuid": "f46c8d32-f119-4f87-9b96-0cbee7449eef", "historyId": "9107ed36be7e4880a2ff9dfb9b79035d", "testCaseId": "6d824c72da181f97caa50844337b058a", "fullName": "Test_MT.TestEOS#test_eos_guest", "labels": [{"name": "story", "value": "Авторизация _P_dit_guest_wifi"}, {"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "8060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}