{"name": "test_bus207", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus207\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')", "trace": "self = <Test_MT.TestOther object at 0x00000191383A8E48>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_TTM_v5\")\n    def test_bus207(self):\n>       assert AutoTest(number, mac, name, '_P_TTM_v5', 'bus207') == True, \"Ошибка в ходе выполнения теста bus207\"\nE       AssertionError: Ошибка в ходе выполнения теста bus207\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')\n\nTest_MT.py:134: AssertionError"}, "attachments": [{"name": "log", "source": "74a6209c-d473-4f8c-a629-70d170a1e453-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "813a6234-c6a2-4643-a0ef-faa152be940e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c2310a42-d708-41e2-97a4-673f298f70ee-attachment.txt", "type": "text/plain"}], "start": 1652246554662, "stop": 1652246733168, "uuid": "8ed40d11-f22e-4d34-aef9-3b5b096b415a", "historyId": "3369cd05539770f0c09511c571a4094b", "testCaseId": "bc0a014b62f50edbcb39f57be6bfbe2a", "fullName": "Test_MT.TestOther#test_bus207", "labels": [{"name": "story", "value": "Авторизация _P_TTM_v5"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "9796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}