{"name": "test_eos_beeline", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')", "trace": "self = <Test_MT.TestEOS object at 0x0000018A051BF048>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_beeline\")\n    def test_eos_beeline (self):\n>       assert AutoTest(number, mac, name, '_P_dit_beeline', 'beeline') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_beeline\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')\n\nTest_MT.py:86: AssertionError"}, "attachments": [{"name": "log", "source": "191bad60-869b-42bd-8856-7973f6fd3e01-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "eb9d9b12-92d1-40a5-b10c-b4535a7d6aa7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "384b4a95-86cf-4ef0-b078-2a18089f1334-attachment.txt", "type": "text/plain"}], "start": 1651770683149, "stop": 1651770806061, "uuid": "6c6072d4-6623-47e5-8252-948688de70cf", "historyId": "e22ae9fe984354816df9ee71a888005b", "testCaseId": "6681ab98911e15b281dbcc8f74f0892b", "fullName": "Test_MT.TestEOS#test_eos_beeline", "labels": [{"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_dit_beeline"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}