{"name": "test_eos_beeline", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')", "trace": "self = <Test_MT.TestEOS object at 0x000001A3899C86A0>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_beeline\")\n    def test_eos_beeline (self):\n>       assert AutoTest(number, mac, name, '_P_dit_beeline', 'beeline') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_beeline\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')\n\nTest_MT.py:86: AssertionError"}, "attachments": [{"name": "log", "source": "9a5fcd99-3e09-406c-b5bf-5698ee3afcf6-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "09989014-8e81-412a-b572-b91049955699-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9de3a654-94f7-4d4c-b006-2e8edb25a69f-attachment.txt", "type": "text/plain"}], "start": 1652024638457, "stop": 1652024761320, "uuid": "f47ff91a-22dc-448b-9c51-71671ee13d39", "historyId": "e22ae9fe984354816df9ee71a888005b", "testCaseId": "6681ab98911e15b281dbcc8f74f0892b", "fullName": "Test_MT.TestEOS#test_eos_beeline", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_dit_beeline"}, {"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}