{"name": "test_metro", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_metro\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_metro', 'metro')", "trace": "self = <Test_MT.TestOther object at 0x00000211ABCBB278>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_metro\")\n    def test_metro (self):\n>       assert AutoTest(number, mac, name, '_P_metro', 'metro') == True, \"Ошибка в ходе выполнения теста _P_metro\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_metro\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_metro', 'metro')\n\nTest_MT.py:101: AssertionError"}, "attachments": [{"name": "log", "source": "69c4fb82-e3a2-440d-a2be-cbe4c57c1e9e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3dad65c1-ff34-46d6-bd95-4161fb219322-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ce03af78-b484-4964-b67d-78ed6cc00daa-attachment.txt", "type": "text/plain"}], "start": 1652186943946, "stop": 1652187095510, "uuid": "8940ed31-6014-475d-a089-a7fcfcc27c4e", "historyId": "8acea32337f99371ab552a6e37fcab1f", "testCaseId": "9d6c6d19f4d4c8de89bf750f8280ce72", "fullName": "Test_MT.TestOther#test_metro", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_metro"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "2864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}