{"name": "test_eos_beeline", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')", "trace": "self = <Test_MT.TestEOS object at 0x00000136FFB7F320>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_beeline\")\n    def test_eos_beeline (self):\n>       assert AutoTest(number, mac, name, '_P_dit_beeline', 'beeline') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_beeline\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_beeline\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_beeline', 'beeline')\n\nTest_MT.py:86: AssertionError"}, "attachments": [{"name": "log", "source": "0fa44c35-39b9-4a93-9bd0-b32761d3c42b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d7debdc1-fcc2-4693-acc3-be7b2a3a2702-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5376c999-b9da-487d-9532-dd77fbe99ac1-attachment.txt", "type": "text/plain"}], "start": 1652057047266, "stop": 1652057204035, "uuid": "de324d39-f585-4c20-a83d-7d831efc2e7d", "historyId": "e22ae9fe984354816df9ee71a888005b", "testCaseId": "6681ab98911e15b281dbcc8f74f0892b", "fullName": "Test_MT.TestEOS#test_eos_beeline", "labels": [{"name": "story", "value": "Авторизация _P_dit_beeline"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "6820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}