{"name": "test_bus207", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus207\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')", "trace": "self = <Test_MT.TestOther object at 0x000002A712A6A470>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_TTM_v5\")\n    def test_bus207(self):\n>       assert AutoTest(number, mac, name, '_P_TTM_v5', 'bus207') == True, \"Ошибка в ходе выполнения теста bus207\"\nE       AssertionError: Ошибка в ходе выполнения теста bus207\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')\n\nTest_MT.py:134: AssertionError"}, "attachments": [{"name": "log", "source": "a08860b2-af9e-40a8-85b0-2191bbdca3eb-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "69c550e8-ebc8-4d41-bd5c-c9997cf5012d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "04af61c0-1e5e-403f-a8c3-caa19e9d6536-attachment.txt", "type": "text/plain"}], "start": 1651917423932, "stop": 1651917622565, "uuid": "0cbbd9c4-2c56-4e9a-a870-2fe21a84485f", "historyId": "3369cd05539770f0c09511c571a4094b", "testCaseId": "bc0a014b62f50edbcb39f57be6bfbe2a", "fullName": "Test_MT.TestOther#test_bus207", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_TTM_v5"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "1488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}