{"name": "test_bus154", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus154\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')", "trace": "self = <Test_MT.TestOther object at 0x00000210F20E1550>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_mvf_bus\")\n    def test_bus154(self):\n>       assert AutoTest(number, mac, name, '_P_mvf_bus', 'bus154') == True, \"Ошибка в ходе выполнения теста bus154\"\nE       AssertionError: Ошибка в ходе выполнения теста bus154\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')\n\nTest_MT.py:129: AssertionError"}, "attachments": [{"name": "log", "source": "4b63b277-c2cf-41e8-87d8-72f09d2ee51c-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "39b417a4-686a-4717-a094-f60d711fa91d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d90d5743-3dfa-4a5a-b6d5-a4d089e4e98e-attachment.txt", "type": "text/plain"}], "start": 1651231699470, "stop": 1651231882563, "uuid": "b72a39ce-bd5d-455b-a378-e2f08259cd2a", "historyId": "6c3f8a24dd4f4f99790af4fc37371378", "testCaseId": "aa57b99d04c859b0fd67a10830cbc1f3", "fullName": "Test_MT.TestOther#test_bus154", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_mvf_bus"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "15900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}