{"name": "test_metro", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_metro\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_metro', 'metro')", "trace": "self = <Test_MT.TestOther object at 0x0000021D163084E0>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_metro\")\n    def test_metro (self):\n>       assert AutoTest(number, mac, name, '_P_metro', 'metro') == True, \"Ошибка в ходе выполнения теста _P_metro\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_metro\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_metro', 'metro')\n\nTest_MT.py:101: AssertionError"}, "attachments": [{"name": "log", "source": "833d0a54-fd2c-48f9-8af9-d4c5419718f7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "20a60820-50e1-4980-994b-ffc7c5e21041-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "b5d4bb6a-9bb6-44d9-b790-10b56b20ab45-attachment.txt", "type": "text/plain"}], "start": 1651987047877, "stop": 1651987179771, "uuid": "e21a0a40-01c0-4388-bd52-966f7f058140", "historyId": "8acea32337f99371ab552a6e37fcab1f", "testCaseId": "9d6c6d19f4d4c8de89bf750f8280ce72", "fullName": "Test_MT.TestOther#test_metro", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "story", "value": "Авторизация _P_metro"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "9860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}